-- liquibase formatted sql
-- changeset alejandro:0001

CREATE OR REPLACE TABLE products(
	id INT PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(512) UNIQUE NOT NULL CHECK (TRIM(name) != ''),
	description TEXT CHECK (TRIM(description) != ''),
	cost DECIMAL(19, 4) NOT NULL
);

CREATE OR REPLACE TABLE product_info(
	id INT PRIMARY KEY AUTO_INCREMENT,
	product_id INT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
	info TEXT CHECK (TRIM(info) != '')
);

CREATE OR REPLACE TABLE orders(
	id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	time DATETIME NOT NULL
);

CREATE OR REPLACE TABLE order_product(
	order_id BIGINT UNSIGNED NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
	product_id INT NOT NULL REFERENCES products(id),
	PRIMARY KEY (order_id, product_id)
);

CREATE OR REPLACE TABLE order_info(
	id INT PRIMARY KEY AUTO_INCREMENT,
	order_id BIGINT UNSIGNED NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
	info TEXT CHECK (TRIM(info) != '')
);
