POST http://localhost:8080/api/products/demo?count=10&minPrice=50&maxPrice=1000
###
GET http://localhost:8080/api/products/random?count=10
###
POST http://localhost:8080/api/orders/random?itemsCount=2
###
POST http://localhost:8080/api/orders/random/bulk?visitors=100&conversionRate=0.1&productViewsPerVisitor=12&maxWaitingTimeSeconds=30&minItemsPerOrder=1&maxItemsPerOrder=3
