### Delete all orders
DELETE http://localhost:8080/api/orders

### Delete all products
DELETE http://localhost:8080/api/products

### Generate random products
POST http://localhost:8080/api/products/demo
	?count=1000
	&minPrice=50
	&maxPrice=1000

### Get random product
GET http://localhost:8080/api/products

### Views
GET http://localhost:8080/api/views
	?count=5
	&intervalSeconds=1
	&timeoutMillis=1000

### Orders
GET http://localhost:8080/api/orders
	?count=1
	&itemsPerOrder=2
	&intervalSeconds=1
	&timeoutMillis=1000
