### Delete all orders
GET http://localhost:8080/api/orders/deleteAll

### Delete all products
GET http://localhost:8080/api/products/deleteAll

### Generate random products
GET http://localhost:8080/api/products/createDemoData?count=1000&minPrice=5&maxPrice=3000

### Get random product
GET http://localhost:8080/api/products/findRandom

### Simulate product views
GET http://localhost:8080/api/simulation/views?count=5&intervalSeconds=1

### Simulate orders
GET http://localhost:8080/api/simulation/orders?count=1&itemsPerOrder=2&intervalSeconds=1
