### Delete all orders
DELETE http://localhost:8080/api/orders/

### Delete all products
DELETE http://localhost:8080/api/products/

### Generate random products
POST http://localhost:8080/api/products/demo/
	?count=1000
	&minPrice=50
	&maxPrice=1000

### Get random product
GET http://localhost:8080/api/products/

### Generate 1 random order with 1 product
POST http://localhost:8080/api/orders/random/
	?visitors=1
	&conversionRate=1
	&productViewsPerVisitor=10
	&maxWaitingTimeMillis=2000
	&itemsPerOrder=1
	&maxBudgetPerVisitor=1000

### Generate random orders
POST http://localhost:8080/api/orders/random/
	?visitors=10
	&conversionRate=0.02
	&productViewsPerVisitor=10
	&maxWaitingTimeMillis=2000
	&itemsPerOrder=2
	&maxBudgetPerVisitor=1000

### Black Friday!
POST http://localhost:8080/api/orders/random/
	?visitors=1000
	&conversionRate=0.04
	&productViewsPerVisitor=15
	&maxWaitingTimeMillis=2000
	&itemsPerOrder=3
	&maxBudgetPerVisitor=1000

###
POST http://localhost:8080/api/simulation/
	?productViews=100
	&orderCount=100
	&itemCount=3
	&maxWaitTimeMillis=1000

